### ISSUE TITLE
Pinpoint Agent not able to connect to pinpoint dockerized collector

### ISSUE THREAD

**Issue by sattishv** [naver/pinpoint-docker#17]
Hi team,

We are facing connectivity issues while connecting to dockerized collector from pinpoint agent which is successfully hooked to dockerized application. Attached the output of pinpoint collector port used.

CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS              PORTS                                                                                                                            NAMES

559e8b9d9f2f        pinpointdocker/pinpoint-collector:1.8.2   "/usr/local/bin/star…"   3 days ago          Up 2 days           8080/tcp, 0.0.0.0:9994-9996->9994-9996/tcp, 0.0.0.0:9995-9996->9995-9996/udp                                                     pinpoint-collector

Env:
collector deployed on Mac whereas the agent resides on ubuntu trusty

Agent log shows the error message as:
2019-03-01 03:48:57 [WARN ](c.n.p.p.AgentInfoSender            ) request failed.
com.navercorp.pinpoint.rpc.PinpointSocketException: reconnecting...
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.newReconnectException(ReconnectStateClientHandler.java:84)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.reconnectFailureFuture(ReconnectStateClientHandler.java:70)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.request(ReconnectStateClientHandler.java:89)
        at com.navercorp.pinpoint.rpc.client.DefaultPinpointClient.request(DefaultPinpointClient.java:123)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:344)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:230)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.sendPacket(TcpDataSender.java:208)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender$1.execute(TcpDataSender.java:108)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:166)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:96)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run(AsyncQueueingExecutor.java:79)
        at java.lang.Thread.run(Thread.java:745)
2019-03-01 03:48:57 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.239.51.21', port=9994}
2019-03-01 03:48:57 [INFO ](.p.r.c.DefaultPinpointClientHandler) DefaultPinpointClientHandler@6c152975 initReconnect() started.
2019-03-01 03:48:57 [INFO ](.n.p.r.c.PinpointClientHandlerState) DefaultPinpointClientHandler@6c152975 stateTo() completed. Socket state change success(updateWanted:BEING_CONNECT ,before:NONE ,current:BEING_CONNECT).
2019-03-01 03:48:57 [INFO ](.p.r.c.DefaultPinpointClientHandler) DefaultPinpointClientHandler@6c152975 initReconnect() completed.
2019-03-01 03:49:02 [INFO ](.p.r.c.DefaultPinpointClientHandler) DefaultPinpointClientHandler@6c152975 channelClosed() started.
2019-03-01 03:49:02 [INFO ](.n.p.r.c.PinpointClientHandlerState) DefaultPinpointClientHandler@6c152975 stateTo() completed. Socket state change success(updateWanted:CONNECT_FAILED ,before:BEING_CONNECT ,current:CONNECT_FAILED).
2019-03-01 03:49:02 [INFO ](c.n.p.r.c.PinpointClientHandshaker ) PinpointClientHandshaker@5c20e602 handshakeAbort() started.
2019-03-01 03:49:02 [WARN ](.p.r.c.DefaultPinpointClientHandler) DefaultPinpointClientHandler@6c152975 exceptionCaught() occurred. state:CONNECT_FAILED. Caused:connection timed out: /10.239.51.21:9994
org.jboss.netty.channel.ConnectTimeoutException: connection timed out: /10.239.51.21:9994
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:139)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:83)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2019-03-01 03:49:02 [INFO ](c.n.p.r.c.PinpointClientHandshaker ) PinpointClientHandshaker@5c20e602 unexpected state

Agent options used:

 -javaagent:/opt/pinpoint/pinpoint-bootstrap-1.8.2.jar, -Dpinpoint.agentId=XXXX, -Dpinpoint.applicationName=UBDS,

We were able to connect if we deploy all components of pinpoint on the same host.

Thanks
Sattish.

**Comment by RoySRose** [comment]
@sattishv 

It looks like Pinpoint-Agent can't find Pinpoint-Collector.
Have you changed the IP address in `.env`?
Since the Collector server has been replaced. So should the IP setting for Pinpoint-Agent.

**Comment by sattishv** [comment]
Hi Roy,

I forgot to mention the platform details. We installed the dockerized collector and web version on MacOS whereas the agent resides in Linux(ubuntu). Would that be an issue. 
Regarding your qusetions
Yes changed the ip address to collector version in pinpoint.config available in pinpoint agent folder.
Not sure on the .env file where should i look for. is the linux env file.

Thanks
Sattish

**Comment by sattishv** [comment]
Hi Roy,

The installation was successful when we installed all components in one vm means agent hooked to a application which resides on container and all other components on the host vm. agent log displayed connection established as 
![screen shot 2019-03-04 at 11 21 04 pm](https://user-images.githubusercontent.com/7449241/53752287-3eda6600-3ed4-11e9-92c6-43f3f60f53b6.png)
success but i couldnt see any transaction trace in the Web UI. 

Note: Since we had a port conflict we changed port numbers for Hbase,mysql and flint in docker-compose.yml and restarted the components 

Agent Log:
2019-03-04 09:41:37 [INFO ](c.n.p.p.r.CommandDispatcher        ) MessageReceived handleStreamCreate BasicStreamPacket{streamChannelId=4} ServerStreamChannel[Channel:[id: 0x240fafc8, /10.180.176.96:40358 => /X.X.X.X:9994], StreamId:4, State:CONNECT_ARRIVED].
2019-03-04 09:41:37 [INFO ](.n.p.p.r.s.ActiveThreadCountService) streamCommandService object:TCmdActiveThreadCount(), streamChannelContext:ServerStreamChannel[Channel:[id: 0x240fafc8, /10.180.176.96:40358 => /X.X.X.X:9994], StreamId:4, State:CONNECT_ARRIVED].
2019-03-04 09:41:37 [INFO ](.n.p.p.r.s.ActiveThreadCountService) eventPerformed. ServerStreamChannel:ServerStreamChannel[Channel:[id: 0x240fafc8, /X.X.X.X:40358 => /10.180.176.96:9994], StreamId:4, State:CONNECTED]., StreamChannelStateCode:CONNECTED.
2019-03-04 09:41:37 [INFO ](.n.p.p.r.s.ActiveThreadCountService) turn on ActiveThreadCountTimerTask.
2019-03-04 09:45:24 [INFO ](.n.p.p.r.s.ActiveThreadCountService) eventPerformed. ServerStreamChannel:ServerStreamChannel[Channel:[id: 0x240fafc8, /X.X.X.X:40358 => /X.X.X.X:9994], StreamId:4, State:CLOSED]., StreamChannelStateCode:CLOSED.

**Comment by RoySRose** [comment]
Hello, @sattishv 

>Yes changed the ip address to collector version in pinpoint.config available in pinpoint agent folder.
Not sure on the .env file where should i look for. is the linux env file.

I was talking about `.env` file in pinpoint-docker [repo](https://github.com/naver/pinpoint-docker)
As you can see in the docker file. The IP address is replaced to the ones in `.env` file.

About the log. 
1) You should look at Pinpoint-Collector log to check if the data is collected from Pinpoint-Agent to Pinpoint-Collector. and Pinpoint-Collector -> Hbase
2) Check Pinpoint-Web log to see if data from hbase is correctly retrieved.

**Comment by aviranmz** [comment]
Hi we have the same issue - can you please advise?  we see the server reigstered but no trans - docker and the app is running on local machine...
![image](https://user-images.githubusercontent.com/34619740/53807246-bdc4b280-3f57-11e9-849d-41d4fb140704.png) as you can see the server is up but no trans

**Comment by sattishv** [comment]
Hi Roy,

We made the change in .env file replaced IP_ADDRESS to collector IP. But still none of the trace been instrumented. Agent and web logs looks ok we dont see any exceptions or errors but collector logs showed below warnings

2019-03-05 16:49:52 [INFO ](.c.r.t.t.AgentLifeCycleEventHandler) Handle lifecycle event - pinpointServer:DefaultPinpointServer@58810205(remote:/10.180.176.96:36558, state:RUN_DUPLEX, healthCheckState:RECEIVED), state:Running
2019-03-05 16:50:17 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:50:22 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:50:47 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:50:52 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:51:17 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:51:22 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:51:43 [INFO ](.c.r.t.t.AgentLifeCycleEventHandler) Handle lifecycle event - pinpointServer:DefaultPinpointServer@198c1971(remote:/172.20.0.1:43782, state:RUN_DUPLEX, healthCheckState:RECEIVED), state:Running
2019-03-05 16:51:47 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:51:52 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:52:17 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:52:22 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:52:47 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:52:52 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:53:17 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:53:22 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:53:47 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null
2019-03-05 16:53:52 [WARN ](c.n.p.c.s.SendAgentStatService     ) not send flink server. Because FlinkTcpDataSender is null

Sattish.

**Comment by RoySRose** [comment]
@sattishv 

flink is for certain feature.
[setting up flink](https://github.com/naver/pinpoint-docker#flink-configuration-optional)

Have you changed all the IP address in `.env` file?

need to set all the IPs that you've changed,
which will be HBASE_HOST, COLLECTOR_IP,  `.env` file
if you separated zookeeper than, zookeeper address will be needed also.

Taking a look at the architecture [here](https://naver.github.io/pinpoint/overview.html#architecture) may help you with the settings

**Comment by RoySRose** [comment]
Also, take a look at Pinpoint-Agent's log if they are successfully connected to Collector.
and Pinpoint-Web's log to check if they are successfully connected to Hbase.

Check out [network test helper](https://naver.github.io/pinpoint/troubleshooting_network.html).
I know this works, but I didn't use it with docker images. If you get to try this.
Happy to hear the results.

**Comment by RoySRose** [comment]
@sattishv 

>I forgot to mention the platform details. We installed the dockerized collector and web version on MacOS whereas the agent resides in Linux(ubuntu). Would that be an issue.
Regarding your qusetions

I'm not sure, But I don't think this would be the issue.
Because, DOCKER itself is designed to be free from these kind of infra issues.

**Comment by RoySRose** [comment]
@sattishv @aviranmz 

IF you have cusomized the docker image to meet your need.
Please take a look at these issues
https://github.com/naver/pinpoint/issues/2406
https://github.com/naver/pinpoint/issues/2616#issuecomment-280233257

**Comment by sattishv** [comment]
Hi Roy,

Thanks a lot.
![screen shot 2019-03-06 at 2 19 41 pm](https://user-images.githubusercontent.com/7449241/53867991-f9748080-401a-11e9-8392-aa6f9e78ed9d.png)
 it worked atlast by changing application type as SPRING_BOOT and setting profiler.tomcat.conditional.transform=false. We could see the trace now but not in detail.
We use RXJava an async framework. We couldn't trace after async event . Does pinpoint support RXJava if not is their any other way to support that. Please review and confirm

**Comment by RoySRose** [comment]
@sattishv 

Good for you :)
Thanks for sharing the results.

As you can see from the homepage 
https://naver.github.io/pinpoint/main.html#supported-modules
Supported module part is still under-construction for 1.9.0. 
But RxJava is supported from 1.0.0 to 1.3.8.
If you are Using RxJava, it should be traced :)

**Comment by RoySRose** [comment]
Oh.... take a look at [here](https://github.com/naver/pinpoint/tree/master/plugins/rxjava).

**Comment by Xylus** [comment]
Might want to check *pinpoint.config* to see if rxjava tracing is enabled.
