### ISSUE TITLE
Error in line: ARG INSTALL_URL=https://github.com/naver/pinpoint/releases/download/${PINPOINT_VERSION}/pinpoint-agent-${PINPOINT_VERSION}.tar.gz

### ISSUE THREAD

**Issue by Jcmouy** [naver/pinpoint-docker#43]
Hi, first of all thank you very much for this fantastic software. I am trying to upgrade from version 1.8.5 to 2.0.1. But I have the following bugs.
-When I run "docker-compose pull" it fails me because it searches in: https://hub.docker.com/u/pinpointdocker for the 2.0.0 tag, and it doesn't find it because the last update was 6 months ago in version 1.8.5.
-If I decide to execute the following command "docker-compose up -d" I have to change all the lines in Dockerfile that have a variable pinpoint version to a hardcoded one. Example of this:

ARG INSTALL_URL=https://github.com/naver/pinpoint/releases/download/${PINPOINT_VERSION}/pinpoint-agent-${PINPOINT_VERSION}.tar.gz

I must change it to:

ARG INSTALL_URL=https://github.com/naver/pinpoint/releases/download/1.8.5/pinpoint-agent-1.8.5.tar.gz

This is because it can't find version 2.0.0 of this file at that address. This error is replicated in the collector, hbase, mysql, etc.

There is a way to fix this by bringing version 2.0.0 instead of 1.8.5?

Thank you very much.

Greetings

**Comment by pperez** [comment]
Seems like it's tagged on the repo as v2.0.1, if you change all the dockerfiles to that it could work (I'll keep my machine building and see if it succeeds) but i would really like not to build the images by myself and have them on docker hub

**Comment by RoySRose** [comment]
Hello, @Jcmouy @pperez 
Sorry about the inconvenience. There was a critical bug on the release 2.0.0 for users using jvm 9+. 
We've rushed to release 2.0.1. 
Also, there was ONE LETTER change in the download location.
I've just made a PR on it. I believe It will be okay. 

As of this writing, there isn't any image of DockerHUB yet, it will start building 1 by 1.
I'll check on DockerHub later for the result (couldn't test it on Local due to POOOOOOR network here) and share the result on this issue.

**Comment by pperez** [comment]
Heh, no problem, also i had problems building pinpoint-web, seems to be missing a log4j.xml (I guess you are adding it trough the mail.zip file), this makes the sed in the entrypoint to fail and the container to keep on restarting forever

**Comment by pperez** [comment]
Also tried to fix the pinpoint-agent image, the new release seems to have an extra directory.
But now the entrypoint is missing /pinpoint-agent/lib/log4j.xml
Not sure how to fix that one tough ...

The collector has a similar issue, is missing /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/log4j.xml
The web image too, is missing /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/log4j.xml

**Comment by RoySRose** [comment]
@pperez 

Actually, log4j.xml is not in mail.zip. It's from Pinpoint-web itself. 
I think it's due to spring configuration we've adapted for v2.

I'll check on this too. Thank you for sharing

**Comment by Jcmouy** [comment]
Hello, thank you both very much for your prompt response. I pulled the new modifications on both github and dockerhub and the problems that previously occurred no longer occur. 

One bug that did happen was that pinpoint-web restarts again and again as it can't find log4j.xml. I could fix this by loading it locally, previously I opened the war and pasted the 1.8.5 version of the log4j.xml file. I made the following changes to the Dockerfile:

----------------------

ARG PINPOINT_VERSION=${PINPOINT_VERSION:-2.0.1}
#ARG INSTALL_URL=https://github.com/naver/pinpoint/releases/download/v${PINPOINT_VERSION}/pinpoint-web-${PINPOINT_VERSION}.war

COPY /build/scripts/start-web.sh /usr/local/bin/
COPY /build/mail.zip /assets/mail.zip
COPY /build/pinpoint-web.war /usr/local/bin/
RUN chmod a+x /usr/local/bin/start-web.sh
    && rm -rf /usr/local/tomcat/webapps \
    && mkdir -p /usr/local/tomcat/webapps
    && unzip /usr/local/bin/pinpoint-web.war -d /usr/local/tomcat/webapps/ROOT
    && rm -rf /usr/local/bin/pinpoint-web.war
    && curl -SL https://maven.java.net/content/repositories/releases/com/sun/mail/javax.mail/1.5.2/javax.mail-1.5.2.jar -o /usr/local/tomcat/webapps/ROOT/WEB-INF/lib/javax.mail-1.5.2.jar \
    && unzip /assets/mail.zip -d /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/
    && rm -rf /assets/mail.zip

-------------------------------

I couldn't fix a similar error with pinpoint-agent which is continuously restarted because it doesn't find pinpoin.config. This is what the console shows me:

+ sed -i '/profiler.collector.ip=/ s/=.*/=pinpoint-collector/' /pinpoint-agent/pinpoint.config
Thirst: /pinpoint-agent/pinpoint.config: No such file or directory

------------------------------
I tried to run pinpoint-web but it was not possible, at the moment of loading the page it dies and in the log it shows me the following error:

2020-03-16 18:16:43 [ERROR](o.a.h.h.z.ZooKeeperWatcher         ) hconnection-0x8c544dc0x0, quorum=localhost:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:419)
        at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
        at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:105)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.retrieveClusterId(ConnectionManager.java:916)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:659)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:637)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
        at com.navercorp.pinpoint.common.hbase.ConnectionFactoryBean.afterPropertiesSet(ConnectionFactoryBean.java:71)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1689)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1627)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:648)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:145)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1198)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1100)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1534)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1281)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1136)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1064)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:583)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:364)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1269)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:744)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1135)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1869)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


Thank you very much for your trouble.

**Comment by RoySRose** [comment]
@Jcmouy 
The location has been changed due to adaption of spring profiles.
I'm still working on it. I think this will be taken care of today.
As I've mentioned earlier I'll update on this thread on the results.

**Comment by RoySRose** [comment]
Hello, @pperez @Jcmouy 

I've managed to solve a few issued on the v2.0.1 docker image.
 - there was download location changed issue -solved
 - spring profiler was adapted since v2 and cause an issue -solved 
    - missing log4j.xml is related to this issue
 - grpc was adapted since v2 causing port problem -solved
    - taken care of by checking the default port. 

I've managed to test it (worked with the better network today). Looks fine.
![image](https://user-images.githubusercontent.com/20402016/76837444-f0490100-6875-11ea-98e7-edfe92f132ad.png)

But didn't have much time to test the details.
I hope you can give us more feedback if there are any more issues.

About `mail.zip` I plan to remove it before the release of the v2.0.1 docker image as soon as I have time, since so far I know it's included as default in v2

(current release is pre-release)

**Comment by Jcmouy** [comment]
Hello @RoySRose , I chose to start from scratch, cloning the project again, this way there was no conflict with what I had done before. But, in spite of this there are some bugs that continue, I attach capture of them:

-Reinicio continuo:

<a href="https://ibb.co/3cj5t8x"><img src="https://i.ibb.co/KWfcCQt/Problema.png" alt="Problema" border="0"></a>

-Error en  log4j.xml

<a href="https://ibb.co/4fNm38B"><img src="https://i.ibb.co/thCmFqy/Problema-Web.png" alt="Problema-Web" border="0"></a>

-Error en agent

<a href="https://ibb.co/mNH7FfH"><img src="https://i.ibb.co/7kGFNsG/Problema-Agent.png" alt="Problema-Agent" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>tree top view png</a><br />

I don't understand why this is happening?

**Comment by pperez** [comment]
I think there are two fixes missing https://github.com/pperez/pinpoint-docker/commit/18b274d31a5db8b93894e3acc37f14a21ce3300f
But now when i start pinpoint web interface it just a blank screen, seems like it can't connect to zookeeper
pinpoint-web           | 2020-03-17 13:00:25 [WARN ](o.a.h.h.z.RecoverableZooKeeper     ) Unable to create ZooKeeper Connection
pinpoint-web           | java.net.UnknownHostException: {YOUR_RELEASE_ZOOKEEPER_ADDRESS}
pinpoint-web           | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)

I think this is due to YOUR_RELEASE_ZOOKEEPER_ADDRESS beign in /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/profiles/release/pinpoint-web-env.properties
But i'm not sure if this is the only issue i'll find

**Comment by Jcmouy** [comment]
Hi @pperez , you know that the error in the agent that i pointed out keeps happening, it keeps restarting.

**Comment by RoySRose** [comment]
@Jcmouy 
Sorry about that. I did fix the issues you've mentioned yesterday.
But it wasn't included in the PR, don't know why. Maybe I just missed it.

I've managed just fixed the PR and merged.
