### ISSUE TITLE
Pinpoint Agent always report "Connection refused: /127.0.0.1:9993" periodically while startup application

### ISSUE THREAD

**Issue by stephen-liu1974** [naver/pinpoint-docker#54]
Hi @RoySRose
I met the same issue. BTW, we had ever use pinpoint 1.8.5 as APM for our product environment, very good tool, but we really need the new feature which supports spring cloud gateway, so we expect to upgrade to 2.0.1. The following is my env and result,

Version is 2.0.1
Got it from 2.0.1 docker release tar file, and the agent was from Pinpoint (not docker) 2.0.1 release tar. No any changes after download.
Started the server with docker-compose up, and launched my app(spring boot 2.2.x) from my PC (not docker) with the following VM options.
-javaagent:./zz-resource/pinpoint-agent-2.0.1/pinpoint-bootstrap-2.0.1.jar -Dpinpoint.applicationName=upms -Dpinpoint.agentId=upms
And I found the console of my app always output the following exception messages periodically
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
at io.grpc.Status.asRuntimeException(Status.java:526)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9993
Caused by: java.net.ConnectException: Connection refused
... ....

And then I run the linux command, netstat -an | grep 9993, the following output.
udp46 0 0 *.9992 .

At this time, I can access lcoalhost:8079 from browser, but no data collected.

I made one change in docker-compose.yml of root directory.

I changed the ports for image pinpoint-collector,
FROM
ports:

"${COLLECTOR_RECEIVER_AGENT_PORT:-9991}:9991/udp"
"${COLLECTOR_RECEIVER_METADATA_PORT:-9991}:9991/tcp"
"${COLLECTOR_RECEIVER_STAT_PORT:-9992}:9992/udp"
"${COLLECTOR_RECEIVER_SPAN_PORT:-9993}:9993/udp"
TO
ports:
"${COLLECTOR_RECEIVER_AGENT_PORT:-9991}:9991/udp"
"${COLLECTOR_RECEIVER_METADATA_PORT:-9991}:9991/tcp"
"${COLLECTOR_RECEIVER_STAT_PORT:-9992}:9992/tcp"
"${COLLECTOR_RECEIVER_SPAN_PORT:-9993}:9993/tcp"
After this change, TCP port(9992 and 9993) can be connected from the agent of my app while launching, and no socket connection exception thrown again.

But I started all the apps with the same VM options (of course, agentId and applicationName are different), and then access the url (localhost:8079), what it shows is "User -> one app -> MySQL", for gateway, one "User -> gateway", even if the gateway really forwarded the request to one service. For service to service case, no services calling chain was shown.

According to my conclusion, after the change the expose port(9992 and 9993) type from UDP to TCP, data can be collected, but the whole calling chain (between service and service, service and gateway) isn't setup.

**Comment by RoySRose** [comment]
@stephen-liu1974 
as I've answered on #53 
I've exposed Thrift. and changed protocol UDP -> TCP
PR #55 is merged.

The other question, regarding the calling chain between applications.
I don't think this is related to docker container or it's network settings.

**Comment by stephen-liu1974** [comment]
Hi @RoySRose 

Thank you for your fix. 
By now, only one issue still exists, no link between spring cloud gateway and other applications, but the links among applications are ok. At this time, gateway can be shown in pinpoint and the only one link for gateway is from USER.
I didn't make any changes after downloaded the pinpoint-docker-master and run it normally, I launched my app with point-agent-2.0.1 which downloaded from release tar. I used the default protocol GRPC. 
Do you know any other extra setting for Spring Cloud Gateway?

**Comment by RoySRose** [comment]
Hello, @stephen-liu1974 

Hm. I didn't make the Spring Cloud plugin. So, doesn't know much about it.
Why don't you take this to [Pinpoint github repo](https://github.com/naver/pinpoint/issues)

**Comment by stephen-liu1974** [comment]
Hi @RoySRose 

Thank you for your help. I submitted it to Pinpoint github repo yesterday.

I closed this issue.
