### ISSUE TITLE
Cannot Change profiler.transport.grpc.collector.ip in pinpoint-agent-2.0.1/pinpoint.config

### ISSUE THREAD

**Issue by cagri387** [naver/pinpoint-docker#61]
Even I change the `profiler.transport.grpc.collector.ip ` property in pinpoint.config. Application still try to access 127.0.0.1. Why is it like this?

I use version 2.0.1 for both pinpoint-docker and pinpoint-agent.

Logs on startup:

```
2020-04-15 12:53:25 [WARN ](c.n.p.p.AgentInfoSender            ) request failed.
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at pinpoint.agent/pinpoint.agent/io.grpc.Status.asRuntimeException(Status.java:526)
	at pinpoint.agent/pinpoint.agent/io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
	at pinpoint.agent/pinpoint.agent/io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at pinpoint.agent/pinpoint.agent/io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at pinpoint.agent/pinpoint.agent/io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at pinpoint.agent/pinpoint.agent/io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at pinpoint.agent/pinpoint.agent/io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at pinpoint.agent/pinpoint.agent/io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at pinpoint.agent/pinpoint.agent/io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:9991
Caused by: java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:579)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:820)
	at pinpoint.agent/pinpoint.agent/io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at pinpoint.agent/pinpoint.agent/io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at pinpoint.agent/pinpoint.agent/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at pinpoint.agent/pinpoint.agent/io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at pinpoint.agent/pinpoint.agent/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at pinpoint.agent/pinpoint.agent/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at pinpoint.agent/pinpoint.agent/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at pinpoint.agent/pinpoint.agent/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
2020-04-15 12:53:25.640  INFO 13660 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.29]
2020-04-15 12:53:25 [WARN ](c.n.p.p.AgentInfoSender            ) request failed.
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at pinpoint.agent/pinpoint.agent/io.grpc.Status.asRuntimeException(Status.java:526)
	at pinpoint.agent/pinpoint.agent/io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
	at pinpoint.agent/pinpoint.agent/io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at pinpoint.agent/pinpoint.agent/io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at pinpoint.agent/pinpoint.agent/io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at pinpoint.agent/pinpoint.agent/io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at pinpoint.agent/pinpoint.agent/io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at pinpoint.agent/pinpoint.agent/io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at pinpoint.agent/pinpoint.agent/io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:9991
```

**Comment by koo-taejin** [comment]
hi @cagri387 

I think you changed the resources/pinpoint.config setting, not /{$env}/pinpoint-env.config.

Please, check above issue at following link,
https://github.com/naver/pinpoint/blob/master/doc/installation.md#profiles-2

thanks :)

**Comment by cagri387** [comment]
hi @koo-taejin 

Yes, you are right. Problem solved then.

Thank you

**Comment by Pastel001** [comment]
a question
when use pinpoint agent,how to specified pinpoint-env.config?
thank you!

**Comment by Pastel001** [comment]
> 
> 
> a question
> when use pinpoint agent,how to specified pinpoint-env.config?
> thank you!
i saw when start pinpoint agent,i can use "Dpinpoint.profiler.profiles.active=${SPRING_PROFILES}",so if i dont use this,which config does pinpoint-agent use?

**Comment by Pastel001** [comment]
> 
> 
> a question
> when use pinpoint agent,how to specified pinpoint-env.config?
> thank you!

i saw when start pinpoint agent,i can use "Dpinpoint.profiler.profiles.active=${SPRING_PROFILES}",so if i dont use this,which config does pinpoint-agent use?
