### ISSUE TITLE
Error while uploading pinpoint-flink-job-2.0.2.jar in Apache Flink Dashboard

### ISSUE THREAD

**Issue by Saptarshi510** [naver/pinpoint-docker#64]
Issues -  my pinpoint setup is running on top of docker , all the services are running well , even the "quickapp" also visible on pinpoint and i am able to see the request coming in.

The problem i am facing now is while uploading the jar - pinpoint-flink-job-2.0.2.jar

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:545)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:419)
	at org.apache.flink.client.program.OptimizerPlanEnvironment.getOptimizedPlan(OptimizerPlanEnvironment.java:80)
	at org.apache.flink.client.program.ClusterClient.getOptimizedPlan(ClusterClient.java:318)
	at org.apache.flink.runtime.webmonitor.handlers.JarActionHandler.getJobGraphAndClassLoader(JarActionHandler.java:72)

-----
Caused by: org.apache.flink.api.common.InvalidProgramException: The LocalStreamEnvironment cannot be used when submitting a program through a client, or running in a TestEnvironment context.
	at org.apache.flink.streaming.api.environment.LocalStreamEnvironment.<init>(LocalStreamEnvironment.java:68)
	at org.apache.flink.streaming.api.environment.LocalStreamEnvironment.<init>(LocalStreamEnvironment.java:58)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.createLocalEnvironment(StreamExecutionEnvironment.java:1626)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.createLocalEnvironment(StreamExecutionEnvironment.java:1612)
	at com.navercorp.pinpoint.flink.Bootstrap.createStreamExecutionEnvironment(Bootstrap.java:163)
	at com.navercorp.pinpoint.flink.StatStreamingVer2Job.start(StatStreamingVer2Job.java:57)
	at com.navercorp.pinpoint.flink.StatStreamingVer2Job.main(StatStreamingVer2Job.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:528)

**Comment by RoySRose** [comment]
Hello, @Saptarshi510 

Have you tried with the docker file on this repo? Because, by the look of issue naver/pinpoint#6811, I think you've tried with your own?

**Comment by Saptarshi510** [comment]
Hello! Roy , 
Both the issues are different and reported by myself only . 

1 issue #6811 - The Dockerfile which is mentioned by vikas is to enable pinpoint to sample application to report in pinpoint controller and like the example application (qucikapp) mentioned in the docker-compose .yml  provided by pinpoint team. 

2 issue #64 - it is related to - Flink configuration (optional) The Pinpoint-Flink is necessary to use 'Application Inspector' feature. 
https://github.com/naver/pinpoint-docker - Check for Application Inspector section.
When i try to enable the Application Inspector . 


Thanks!
