### ISSUE TITLE
when i map volume to a path，error 

### ISSUE THREAD

**Issue by kevinzu007** [naver/pinpoint-docker#72]
我在docker-compose.yml 中对 pinpoint-hbase volumes做了映射，（others keep default）：
```
 pinpoint-hbase:
   ......
    volumes:
      - ./data/hbase:/home/pinpoint/hbase
      - ./data/zookeeper:/home/pinpoint/zookeeper
```
然后就出现启动，打开首页，就会出错，显示‘applicationList.pinpoint’一直在那里转呀转呀的。为什么呀？不科学呀

部分错误日志如下：
```
pinpoint-web          | 2020-07-22 01:36:01 [ERROR](o.s.b.c.s.AbstractStep             ) Encountered an error executing step alarmStep in job alarmJob
pinpoint-web          | com.navercorp.pinpoint.common.hbase.HbaseSystemException: ApplicationIndex; nested exception is org.apache.hadoop.hbase.TableNotFoundException: ApplicationIndex
pinpoint-web          | 	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.execute(HbaseTemplate2.java:763)
pinpoint-web          | 	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.find(HbaseTemplate2.java:190)
pinpoint-web          | 	at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.find(HbaseTemplate2.java:219)
pinpoint-web          | 	at com.navercorp.pinpoint.web.dao.hbase.HbaseApplicationIndexDao.selectAllApplicationNames(HbaseApplicationIndexDao.java:75)
pinpoint-web          | 	at com.navercorp.pinpoint.web.alarm.AlarmReader.beforeStep(AlarmReader.java:69)
pinpoint-web          | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
pinpoint-web          | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
pinpoint-web          | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
pinpoint-web          | 	at java.lang.reflect.Method.invoke(Method.java:498)
pinpoint-web          | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
pinpoint-web          | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
pinpoint-web          | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
pinpoint-web          | 	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
pinpoint-web          | 	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
pinpoint-web          | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
pinpoint-web          | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
pinpoint-web          | 	at com.sun.proxy.$Proxy53.beforeStep(Unknown Source)
pinpoint-web          | 	at org.springframework.batch.core.listener.CompositeStepExecutionListener.beforeStep(CompositeStepExecutionListener.java:77)
pinpoint-web          | 	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:196)
pinpoint-web          | 	at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:139)
pinpoint-web          | 	at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:136)
pinpoint-web          | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
pinpoint-web          | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
pinpoint-web          | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
pinpoint-web          | 	at java.lang.Thread.run(Thread.java:748)
pinpoint-web          | Caused by: org.apache.hadoop.hbase.TableNotFoundException: ApplicationIndex
pinpoint-web          | 	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegionInMeta(ConnectionManager.java:1301)
pinpoint-web          | 	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1192)
......
```

**Comment by RoySRose** [comment]
Hello, @kevinzu007 

Though I'm trying to learn Chinese, I don't fully understand what you're trying to say. Please translate it for others too.

By the look of the log. It looks like tthe table isn't created.

**Comment by kevinzu007** [comment]
> Hello, @kevinzu007
> 
> Though I'm trying to learn Chinese, I don't fully understand what you're trying to say. Please translate it for others too.
> 
> By the look of the log. It looks like tthe table isn't created.

i'm so sorry ,
i only modify part of pinpoint-hbase in docker-compose.yml, look:
 pinpoint-hbase:
   ......
    volumes:
      - ./data/hbase:/home/pinpoint/hbase
      - ./data/zookeeper:/home/pinpoint/zookeeper
......
just modify this , when i start it (docker-compose up -d), open the pinpoint-web via my brower. word ‘applicationList.pinpoint’ keep loading on The home page. why?
Please see the first post for the error message

**Comment by RoySRose** [comment]
@kevinzu007 

As I've mentioned earlier.

it's because there was problem with the database, check the table if it's properly created.
Must be because of what you've changed

**Comment by kevinzu007** [comment]
@RoySRose 
oh, I just test it again
I've commented out the 'pinpoint-quickstart' and 'pinpoint-agent' sections and modified all the volumes sections, as follows:
pinpoint-hbase:
```    volumes:
      #- /home/pinpoint/hbase
      - ./data/hbase:/home/pinpoint/hbase
      #- /home/pinpoint/zookeeper
      - ./data/zookeeper:/home/pinpoint/zookeeper
```
pinpoint-mysql:
```    volumes:
      #- mysql_data:/var/lib/mysql
      - ./data/mysql_data:/var/lib/mysql
```

**Complete docker- compose.yml  documents are as follows:** 
```
version: "3.6"

services:
  pinpoint-hbase:
    build:
      context: ./pinpoint-hbase/
      dockerfile: Dockerfile
      args:
        - PINPOINT_VERSION=${PINPOINT_VERSION}

    container_name: "${PINPOINT_HBASE_NAME}"
    image: "pinpointdocker/pinpoint-hbase:${PINPOINT_VERSION}"
    networks:
      - pinpoint

    volumes:
      #- /home/pinpoint/hbase
      - ./data/hbase:/home/pinpoint/hbase
      #- /home/pinpoint/zookeeper
      - ./data/zookeeper:/home/pinpoint/zookeeper
    expose:
      # zookeeper
      - "2181"
      # HBase Master API port
      - "60000"
      # HBase Master Web UI
      - "16010"
      # Regionserver API port
      - "60020"
      # HBase Regionserver web UI
      - "16030"
    ports:
      - "${EXTERNAL_HBASE_PORT:-2181}:2181"
      - "60000:60000"
      - "16010:16010"
      - "60020:60020"
      - "16030:16030"
    restart: always

  pinpoint-mysql:
    build:
      context: ./pinpoint-mysql/
      dockerfile: Dockerfile
      args:
        - PINPOINT_VERSION=${PINPOINT_VERSION}

    container_name: pinpoint-mysql
    restart: always
    image: "pinpointdocker/pinpoint-mysql:${PINPOINT_VERSION}"
    hostname: pinpoint-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

    volumes:
      #- mysql_data:/var/lib/mysql
      - ./data/mysql_data:/var/lib/mysql
    networks:
      - pinpoint

  pinpoint-web:
    build:
      context: ./pinpoint-web/
      dockerfile: Dockerfile
      args:
        - PINPOINT_VERSION=${PINPOINT_VERSION}

    container_name: "${PINPOINT_WEB_NAME}"
    image: "pinpointdocker/pinpoint-web:${PINPOINT_VERSION}"

    depends_on:
      - pinpoint-hbase
      - pinpoint-mysql
    restart: always
    expose:
      - "8080"
      - "9997"
    ports:
      - "9997:9997"
      - "${WEB_PAGE_PORT:-8080}:8080"
    environment:
      - JAVA_OPTS="-Dspring.profiles.active=${SPRING_PROFILES},batch"
      - SPRING_PROFILES=${SPRING_PROFILES}
      - CLUSTER_ENABLE=${CLUSTER_ENABLE}
      - CLUSTER_ZOOKEEPER_ADDRESS=${CLUSTER_ZOOKEEPER_ADDRESS}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ANALYTICS=${ANALYTICS}
      - HBASE_HOST=${HBASE_HOST}
      - HBASE_PORT=${HBASE_PORT}
      - DEBUG_LEVEL=${WEB_DEBUG_LEVEL}
      - CONFIG_SHOW_APPLICATIONSTAT=${CONFIG_SHOW_APPLICATIONSTAT}
      - BATCH_ENABLE=${BATCH_ENABLE}
      - BATCH_SERVER_IP=${BATCH_SERVER_IP}
      - BATCH_FLINK_SERVER=${BATCH_FLINK_SERVER}
      - JDBC_DRIVER=${JDBC_DRIVER}
      - JDBC_URL=${JDBC_URL}
      - JDBC_USERNAME=${JDBC_USERNAME}
      - JDBC_PASSWORD=${JDBC_PASSWORD}
      - MAIL_SERVER_URL=${MAIL_SERVER_URL}
      - MAIL_SERVER_PORT=${MAIL_SERVER_PORT}
      - MAIL_SERVER_USERNAME=${MAIL_SERVER_USERNAME}
      - MAIL_SERVER_PASSWORD=${MAIL_SERVER_PASSWORD}
      - MAIL_SENDER_ADDRESS=${MAIL_SENDER_ADDRESS}
      - MAIL_TRANSPORT_PROTOCOL=${MAIL_TRANSPORT_PROTOCOL}
      - MAIL_SMTP_PORT=${MAIL_SMTP_PORT}
      - MAIL_SMTP_AUTH=${MAIL_SMTP_AUTH}
      - MAIL_SMTP_STARTTLS_ENABLE=${MAIL_SMTP_STARTTLS_ENABLE}
      - MAIL_SMTP_STARTTLS_REQUIRED=${MAIL_SMTP_STARTTLS_REQUIRED}
      - MAIL_DEBUG=${MAIL_DEBUG}
    links:
      - "pinpoint-mysql:pinpoint-mysql"
    networks:
      - pinpoint

  pinpoint-collector:
    build:
      context: ./pinpoint-collector/
      dockerfile: Dockerfile
      args:
        - PINPOINT_VERSION=${PINPOINT_VERSION}

    container_name: "${PINPOINT_COLLECTOR_NAME}"
    image: "pinpointdocker/pinpoint-collector:${PINPOINT_VERSION}"

    depends_on:
      - pinpoint-hbase
    restart: always
    expose:
      - "9991"
      - "9992"
      - "9993"
      - "9994"
      - "9995"
      - "9996"
    ports:
      - "${COLLECTOR_RECEIVER_AGENT_PORT:-9991}:9991/udp"
      - "${COLLECTOR_RECEIVER_METADATA_PORT:-9991}:9991/tcp"
      - "${COLLECTOR_RECEIVER_STAT_PORT:-9992}:9992/tcp"
      - "${COLLECTOR_RECEIVER_SPAN_PORT:-9993}:9993/tcp"
      - "${COLLECTOR_RECEIVER_BASE_PORT:-9994}:9994"
      - "${COLLECTOR_RECEIVER_STAT_UDP_PORT:-9995}:9995/tcp"
      - "${COLLECTOR_RECEIVER_SPAN_UDP_PORT:-9996}:9996/tcp"
      - "${COLLECTOR_RECEIVER_STAT_UDP_PORT:-9995}:9995/udp"
      - "${COLLECTOR_RECEIVER_SPAN_UDP_PORT:-9996}:9996/udp"

    networks:
      - pinpoint
    environment:
      - JAVA_OPTS="-Dspring.profiles.active=${SPRING_PROFILES}"
      - SPRING_PROFILES=${SPRING_PROFILES}
      - CLUSTER_ENABLE=${CLUSTER_ENABLE}
      - CLUSTER_ZOOKEEPER_ADDRESS=${CLUSTER_ZOOKEEPER_ADDRESS}
      - HBASE_HOST=${HBASE_HOST}
      - HBASE_PORT=${HBASE_PORT}
      - FLINK_CLUSTER_ENABLE=${FLINK_CLUSTER_ENABLE}
      - FLINK_CLUSTER_ZOOKEEPER_ADDRESS=${FLINK_CLUSTER_ZOOKEEPER_ADDRESS}
      - DEBUG_LEVEL=${COLLECTOR_DEBUG_LEVEL}

#  pinpoint-quickstart:
#    build:
#      context: ./pinpoint-quickstart/
#      dockerfile: Dockerfile
#
#    container_name: "pinpoint-quickstart"
#    image: "pinpointdocker/pinpoint-quickstart"
#    ports:
#      - "${APP_PORT:-8080}:8080"
#    volumes:
#      - data-volume:/pinpoint-agent
#    environment:
#      JAVA_OPTS: "-javaagent:/pinpoint-agent/pinpoint-bootstrap-${PINPOINT_VERSION}.jar -Dpinpoint.agentId=${AGENT_ID} -Dpinpoint.applicationName=${APP_NAME} -Dpinpoint.profiler.profiles.active=${SPRING_PROFILES}"
#    networks:
#      - pinpoint
#    depends_on:
#      - pinpoint-agent
#
#  pinpoint-agent:
#    build:
#      context: ./pinpoint-agent/
#      dockerfile: Dockerfile
#      args:
#        - PINPOINT_VERSION=${PINPOINT_VERSION}
#
#    container_name: "${PINPOINT_AGENT_NAME}"
#    image: "pinpointdocker/pinpoint-agent:${PINPOINT_VERSION}"
#
#    restart: unless-stopped
#
#    networks:
#      - pinpoint
#    volumes:
#      - data-volume:/pinpoint-agent
#    environment:
#      - SPRING_PROFILES=${SPRING_PROFILES}
#      - COLLECTOR_IP=${COLLECTOR_IP}
#      - PROFILER_TRANSPORT_AGENT_COLLECTOR_PORT=${PROFILER_TRANSPORT_AGENT_COLLECTOR_PORT}
#      - PROFILER_TRANSPORT_METADATA_COLLECTOR_PORT=${PROFILER_TRANSPORT_METADATA_COLLECTOR_PORT}
#      - PROFILER_TRANSPORT_STAT_COLLECTOR_PORT=${PROFILER_TRANSPORT_STAT_COLLECTOR_PORT}
#      - PROFILER_TRANSPORT_SPAN_COLLECTOR_PORT=${PROFILER_TRANSPORT_SPAN_COLLECTOR_PORT}
#      - PROFILER_SAMPLING_RATE=${PROFILER_SAMPLING_RATE}
#      - DEBUG_LEVEL=${AGENT_DEBUG_LEVEL}
#      - PROFILER_TRANSPORT_MODULE=${PROFILER_TRANSPORT_MODULE}
#    depends_on:
#      - pinpoint-collector

  #zookeepers
  zoo1:
    image: zookeeper:3.4
    restart: always
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - pinpoint

  zoo2:
    image: zookeeper:3.4
    restart: always
    hostname: zoo2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    networks:
      - pinpoint

  zoo3:
    image: zookeeper:3.4
    restart: always
    hostname: zoo3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
      - pinpoint

  ##flink
  jobmanager:
    container_name: "${PINPOINT_FLINK_NAME}-jobmanager"
    image: flink:1.3.1
    expose:
      - "6123"
    ports:
      - "${FLINK_WEB_PORT:-8081}:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - pinpoint

  taskmanager:
    container_name: "${PINPOINT_FLINK_NAME}-taskmanager"
    image: flink:1.3.1
    expose:
      - "6121"
      - "6122"
      - "19994"
    ports:
      - "6121:6121"
      - "6122:6122"
      - "19994:19994"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - pinpoint

#volumes:
#  data-volume:
#  mysql_data:

networks:
  pinpoint:
    driver: bridge
```

in brower, Error display is shown below
![图片](https://user-images.githubusercontent.com/2586289/88870846-01a11180-d249-11ea-87ff-278e92fb9ce7.png)
---
Note: the first time I run 'docker compose up - d', open the home page with a browser, and it will usually display 404. I will run 'docker compose down; docker compose up - d' again, which is OK. I usually do this

**Comment by RoySRose** [comment]
Hello, @kevinzu007 

Currently, I'm afraid I can't spare time for the modified version of docker-compose for now.
Meanwhile, you can't check the database. The one you pointed out(applicationList.pinpoint) is often a data retrieval problem with a high probability

**Comment by kevinzu007** [comment]
@RoySRose 
oh, I don't know what to check database. can u give some idea?
---
In fact, it is based on the original version of 'docker'- compose.yml 'file, as long as you modify these two lines, the above error will appear, which is puzzling.
```
      #- /home/pinpoint/hbase
      - ./data/hbase:/home/pinpoint/hbase
      #- /home/pinpoint/zookeeper
      - ./data/zookeeper:/home/pinpoint/zookeeper
```

**Comment by Driver-C** [comment]
@kevinzu007 @RoySRose

**Comment by kevinzu007** [comment]
> @kevinzu007 @RoySRose
> Hi, I had the same problem, but I find out why it's happened.
> 你好，我遇到了同样的问题，不过我知道为什么会这样。
> 
> Tables have been created into the docker image, when docker-compose mount data path to somewhere, this path is empty.
> 数据表被创建在了docker镜像中，当docker-compose挂载数据目录在任意地方的时候，这个目录是空的
> Like I said, talbes have been created into the image, this step in Dockerfile of pinpoint-hbase. Then, mount data path to a new path is So, the tables won't be created in new path.
> 就像我说的，数据表创建在了docker镜像中，这个步骤在pinpoint-hbase的Dockerfile中能看到。所以，所以数据表不会在新的路径创建
> 
> So, if we change the data path, we need create the tables by hand after 'docker-compose up -d'.
> 所以，如果我们要更改数据路径的话，我们需要在执行docker-compose up -d后手动创建数据表。
> 
> Step1. `curl -SL "https://raw.githubusercontent.com/naver/pinpoint/v${PINPOINT_VERSION}/hbase/scripts/hbase-create.hbase" -o ${BASE_DIR}/hbase-create.hbase`
> Step2. `${HBASE_HOME}/bin/hbase shell ${BASE_DIR}/hbase-create.hbase`

是哦，谢谢你哦！

**Comment by RoySRose** [comment]
>是哦，谢谢你哦！
Shì ó, xièxiè nǐ ó!

Thank you, @Driver-C 
Yes, that would probably be the cause.
Thank you for sharing your effort with the community. Also your passion to communicate with others :)
